app = "omegle-clone"

[build]
  # This tells Fly.io to use a Node.js environment
  image = "node:16"  # Replace with your desired Node.js version if needed

[env]
  PORT = "3000"  # Make sure this is the same port your app uses

[[services]]
  http_checks = []
  internal_port = 3000
  processes = ["app"]
  protocol = "tcp"
  ports = [{ port = 80 }]
