app = "omegle-clone"

[build]
  dockerfile = "Dockerfile"  # Pointing to the Dockerfile in the root

[env]
  NODE_ENV = "production"

[deploy]
  release_command = "npm install --production --prefix server"
