app = "omegle-clone"

[build]
  # Use a Node.js environment
  image = "node:22"

[env]
  PORT = "5000"  # Ensure this matches your server.js PORT

[[services]]
  internal_port = 5000  # Use 5000 instead of 3000
  processes = ["app"]
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80
