# fly.toml app configuration file generated for server-crimson-wildflower-4430 on 2025-02-15T05:05:16+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'server-crimson-wildflower-4430'
primary_region = 'arn'

[build]

[env]
  NODE_ENV = "production"
  
[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
