app = "server-crimson-wildflower-4430"
primary_region = "arn"

[build]

[env]
  NODE_ENV = "production"

[http_service]
  # Your Node server listens on port 3000
  internal_port = 3000
  force_https = false   # Disable forced HTTPS for now
  auto_stop_machines = "stop"
  auto_start_machines = true
  # Keep at least 1 machine running
  min_machines_running = 1
  processes = ["app"]

  # Route HTTP traffic only (remove port 443 for now)
  [[http_service.ports]]
    port = 80
    handlers = ["http"]

  # Health check on "/" with more lenient settings
  [[http_service.http_checks]]
    interval = "10s"
    grace_period = "30s"   # Increase grace period to allow slower startups
    method = "get"
    path = "/"
    protocol = "http"
    timeout = "5s"         # Increase timeout

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
