app = "server-crimson-wildflower-4430"
primary_region = "arn"

[build]

[env]
  NODE_ENV = "production"

[http_service]
  # Your Node server listens on port 3000
  internal_port = 3000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  # Ensure at least one machine is always running
  min_machines_running = 1
  processes = ["app"]

  # Route HTTP traffic (port 80)
  [[http_service.ports]]
    port = 80
    handlers = ["http"]

  # Route HTTPS traffic (port 443)
  [[http_service.ports]]
    port = 443
    handlers = ["tls", "http"]

  # Health check on "/" with reasonable settings
  [[http_service.http_checks]]
    interval = "10s"
    grace_period = "30s"
    method = "get"
    path = "/"
    protocol = "http"
    timeout = "5s"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
