app = "server-crimson-wildflower-4430"
primary_region = "arn"

[build]

[env]
  NODE_ENV = "production"

[http_service]
  # Your Node server listens on port 3000
  internal_port = 3000
  force_https = false
  auto_stop_machines = "stop"
  auto_start_machines = true
  # Keep at least 1 machine running
  min_machines_running = 1
  processes = ["app"]

  # Route HTTP (port 80) traffic
  [[http_service.ports]]
    port = 80
    handlers = ["http"]

  # Route HTTPS (port 443) traffic
  [[http_service.ports]]
    port = 443
    handlers = ["tls", "http"]

  # Basic health check on "/"
  [[http_service.http_checks]]
    interval = "10s"
    grace_period = "10s"
    method = "get"
    path = "/"
    protocol = "http"
    timeout = "2s"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
